//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace LIBRARY_MANAGMENT_SOFTWARE
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Hfs_Lib_ManEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Hfs_Lib_ManEntities object using the connection string found in the 'Hfs_Lib_ManEntities' section of the application configuration file.
        /// </summary>
        public Hfs_Lib_ManEntities() : base("name=Hfs_Lib_ManEntities", "Hfs_Lib_ManEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Hfs_Lib_ManEntities object.
        /// </summary>
        public Hfs_Lib_ManEntities(string connectionString) : base(connectionString, "Hfs_Lib_ManEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Hfs_Lib_ManEntities object.
        /// </summary>
        public Hfs_Lib_ManEntities(EntityConnection connection) : base(connection, "Hfs_Lib_ManEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<bok_isu> bok_isu
        {
            get
            {
                if ((_bok_isu == null))
                {
                    _bok_isu = base.CreateObjectSet<bok_isu>("bok_isu");
                }
                return _bok_isu;
            }
        }
        private ObjectSet<bok_isu> _bok_isu;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the bok_isu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobok_isu(bok_isu bok_isu)
        {
            base.AddObject("bok_isu", bok_isu);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Hfs_Lib_ManModel", Name="bok_isu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class bok_isu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new bok_isu object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static bok_isu Createbok_isu(global::System.Int32 id)
        {
            bok_isu bok_isu = new bok_isu();
            bok_isu.Id = id;
            return bok_isu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gr__
        {
            get
            {
                return _Gr__;
            }
            set
            {
                OnGr__Changing(value);
                ReportPropertyChanging("Gr__");
                _Gr__ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gr__");
                OnGr__Changed();
            }
        }
        private global::System.String _Gr__;
        partial void OnGr__Changing(global::System.String value);
        partial void OnGr__Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Borrowers_Name
        {
            get
            {
                return _Borrowers_Name;
            }
            set
            {
                OnBorrowers_NameChanging(value);
                ReportPropertyChanging("Borrowers_Name");
                _Borrowers_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Borrowers_Name");
                OnBorrowers_NameChanged();
            }
        }
        private global::System.String _Borrowers_Name;
        partial void OnBorrowers_NameChanging(global::System.String value);
        partial void OnBorrowers_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Class
        {
            get
            {
                return _Class;
            }
            set
            {
                OnClassChanging(value);
                ReportPropertyChanging("Class");
                _Class = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Class");
                OnClassChanged();
            }
        }
        private global::System.String _Class;
        partial void OnClassChanging(global::System.String value);
        partial void OnClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Book_Name
        {
            get
            {
                return _Book_Name;
            }
            set
            {
                OnBook_NameChanging(value);
                ReportPropertyChanging("Book_Name");
                _Book_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Book_Name");
                OnBook_NameChanged();
            }
        }
        private global::System.String _Book_Name;
        partial void OnBook_NameChanging(global::System.String value);
        partial void OnBook_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Book_Id
        {
            get
            {
                return _Book_Id;
            }
            set
            {
                OnBook_IdChanging(value);
                ReportPropertyChanging("Book_Id");
                _Book_Id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Book_Id");
                OnBook_IdChanged();
            }
        }
        private global::System.String _Book_Id;
        partial void OnBook_IdChanging(global::System.String value);
        partial void OnBook_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Issuing_Date
        {
            get
            {
                return _Issuing_Date;
            }
            set
            {
                OnIssuing_DateChanging(value);
                ReportPropertyChanging("Issuing_Date");
                _Issuing_Date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Issuing_Date");
                OnIssuing_DateChanged();
            }
        }
        private global::System.String _Issuing_Date;
        partial void OnIssuing_DateChanging(global::System.String value);
        partial void OnIssuing_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Due_Date
        {
            get
            {
                return _Due_Date;
            }
            set
            {
                OnDue_DateChanging(value);
                ReportPropertyChanging("Due_Date");
                _Due_Date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Due_Date");
                OnDue_DateChanged();
            }
        }
        private global::System.String _Due_Date;
        partial void OnDue_DateChanging(global::System.String value);
        partial void OnDue_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Received
        {
            get
            {
                return _Received;
            }
            set
            {
                OnReceivedChanging(value);
                ReportPropertyChanging("Received");
                _Received = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Received");
                OnReceivedChanged();
            }
        }
        private global::System.String _Received;
        partial void OnReceivedChanging(global::System.String value);
        partial void OnReceivedChanged();

        #endregion

    
    }

    #endregion

    
}
